import { useEffect, useState } from 'react';
import { ArrowLeft, ChevronLeft, ChevronRight, Layers3, LoaderCircle, RotateCcw, Sparkles, StickyNote, Trash2 } from 'lucide-react';
import type { Chat, Flashcard } from '@/lib/reader-types';
import { MAX_FLASHCARDS } from '@/lib/flashcards';
import { MODELS } from '@/lib/ai-config';

type Props = { filename: string; decks: Chat[]; initialDeckId: string; busy: boolean; model: string; pageCount: number; onGenerate: (count: number) => void; onCancel: () => void; onDelete: (chat: Chat) => void; onPin: (card: Flashcard) => void; onPage: (page: number) => void; onBack: () => void; onConnection: () => void };
export default function FlashcardsPage(props: Props) {
  const [count, setCount] = useState(10);
  const [selected, setSelected] = useState(props.initialDeckId || props.decks[0]?.id || '');
  const [index, setIndex] = useState(0);
  const [revealed, setRevealed] = useState(false);
  const [latest, setLatest] = useState(props.decks[0]?.id || '');
  const deck = props.decks.find(item => item.id === selected) || props.decks[0];
  const cards = deck?.flashcards || [];
  const position = Math.min(index, Math.max(0, cards.length - 1));
  const card = cards[position];
  useEffect(() => {
    const id = props.decks[0]?.id || '';
    if (id !== latest) { setLatest(id); setSelected(id); setIndex(0); setRevealed(false); }
  }, [props.decks, latest]);
  function move(next: number) { setIndex(next); setRevealed(false); }
  return <section className="app-page flashcards-page" aria-labelledby="flashcards-title"><div className="page-heading"><div><span className="eyebrow">A LITTLE PRACTICE GOES A LONG WAY</span><h1 id="flashcards-title" tabIndex={-1}>Flashcards</h1><p className="flashcards-filename">{props.filename}</p></div><button className="button" onClick={props.onBack}><ArrowLeft size={16}/>Back to reader</button></div>
    <div className="flashcards-layout"><section className="settings-card flashcard-generator" aria-label="Generate flashcards"><span className="empty-icon"><Layers3 size={25}/></span><h2>Make a study set</h2><p>Questions on one side. A clear answer on the other.</p><form onSubmit={e => { e.preventDefault(); if (Number.isInteger(count) && count >= 1 && count <= MAX_FLASHCARDS) props.onGenerate(count); }}><label htmlFor="flashcard-count">Number of flashcards</label><input id="flashcard-count" type="number" min={1} max={MAX_FLASHCARDS} step={1} required value={count || ''} disabled={props.busy} onChange={e => setCount(Number(e.target.value))}/><small>Choose 1–{MAX_FLASHCARDS} cards.</small><button type="button" className="model-choice" onClick={props.onConnection}><Sparkles size={13}/>{MODELS.find(item => item.id === props.model)?.label.split(' · ')[0] || props.model}</button><p className="settings-help">Uses your full PDF and saved API key. Larger sets are made in batches of 10; each batch uses API credit.</p><button type="submit" className="button primary" disabled={props.busy || !props.pageCount}>{props.busy ? <LoaderCircle className="spin" size={16}/> : <Sparkles size={16}/>}Generate flashcards</button>{props.busy && <button className="text-button" type="button" onClick={props.onCancel}>Cancel current request</button>}</form><p className="settings-help">Saved automatically with this PDF. Use Save PDF + chats to include your cards in a portable bundle.</p></section>
    <section className="flashcard-study" aria-label="Study flashcards">{deck ? <><div className="deck-toolbar"><label><span>Saved sets</span><select aria-label="Saved flashcard set" value={deck.id} onChange={e => { setSelected(e.target.value); move(0); }}>{props.decks.map(item => <option key={item.id} value={item.id}>{new Date(item.createdAt).toLocaleString()} · {item.flashcards?.length || 0}/{item.flashcardCount} cards</option>)}</select></label><button className="button" aria-label="Delete this flashcard set" onClick={() => props.onDelete(deck)}><Trash2 size={16}/></button></div><p className="deck-status" role="status">{deck.status === 'pending' ? `Making your cards… ${cards.length} of ${deck.flashcardCount} saved.` : deck.status === 'completed' ? `${cards.length} cards · ${deck.model}` : `${cards.length} of ${deck.flashcardCount} cards kept · ${deck.status}. ${deck.error || 'You can study the completed cards or generate another set.'}`}</p>
      {card ? <><button className={'study-card ' + (revealed ? 'is-revealed' : '')} aria-label={revealed ? 'Show question' : 'Reveal flashcard answer'} aria-pressed={revealed} onClick={() => setRevealed(!revealed)}><span className="study-card-label">{revealed ? 'ANSWER' : 'QUESTION'} · {position + 1} / {cards.length}</span>{revealed && <span className="study-question">{card.question}</span>}<span className="study-card-text">{revealed ? card.answer : card.question}</span><span className="study-card-hint"><RotateCcw size={14}/>{revealed ? 'Click to see the question' : 'Think it through, then click to reveal'}</span></button><div className="study-controls"><button className="button" aria-label="Previous flashcard" disabled={position === 0} onClick={() => move(position - 1)}><ChevronLeft size={17}/></button><span>Card {position + 1} of {cards.length}</span><button className="button" aria-label="Next flashcard" disabled={position >= cards.length - 1} onClick={() => move(position + 1)}><ChevronRight size={17}/></button></div><div className="study-actions"><button className="text-button" onClick={() => props.onPage(card.page)}>Read source · PDF page {card.page}</button><button className="text-button" onClick={() => props.onPin(card)}><StickyNote size={14}/>Pin answer as a note</button></div><p className="settings-help">AI-generated study material. Check answers against the cited PDF page.</p></> : <div className="flashcards-empty"><Layers3 size={38}/><p>Your cards will appear here as each batch finishes.</p></div>}</> : <div className="flashcards-empty"><Layers3 size={42}/><h2>Turn reading into recall.</h2><p>Choose a number and generate your first set. Flip each card when you’re ready for the answer.</p></div>}</section></div>
  </section>;
}
