import ReadAloud from './read-aloud';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUp, BookOpen, Lightbulb, LoaderCircle, MessageSquare, Sparkles, Trash2 } from 'lucide-react';
import { MODELS } from '@/lib/ai-config';
import { SUPPORT_LIMIT, SUPPORT_NEEDS, type SupportEntry, type SupportPreferences } from '@/lib/reading-support';

type Props = {
  preferences: SupportPreferences; entries: SupportEntry[]; canReset: boolean; busy: boolean; pending: boolean; model: string;
  onPreferences: (value: SupportPreferences) => void; onAsk: (question: string) => void;
  onCancel: () => void; onDelete: (id?: string) => void; onBack: () => void; onConnection: () => void;
};
const starters = ['Help me start when I have no motivation.', 'I keep rereading the same paragraph. What can I try?', 'Help me read without getting overwhelmed.', 'How can I return after getting distracted?'];
export default function ReadingSupportPage(props: Props) {
  const [question, setQuestion] = useState('');
  const answerEnd = useRef<HTMLDivElement>(null);
  useEffect(() => { answerEnd.current?.scrollIntoView({ block: 'nearest' }); }, [props.entries]);
  const validTime = Number.isInteger(props.preferences.minutes) && props.preferences.minutes >= 1 && props.preferences.minutes <= 120;
  function ask(value: string) { if (!props.busy && validTime && value.trim()) { setQuestion(value); props.onAsk(value); } }
  return <section className="app-page reading-support-page" aria-labelledby="support-title">
    <div className="page-heading"><div><span className="eyebrow">FIND YOUR OWN READING RHYTHM</span><h1 id="support-title" tabIndex={-1}>Focusing Tips for Readers</h1><p>Small steps for paper and book reading, at your pace.</p></div><button className="button" onClick={props.onBack}><ArrowLeft size={16}/>Back to reader</button></div>
    <div className="support-layout"><aside className="settings-card support-preferences" aria-label="Reading support preferences"><span className="empty-icon"><Lightbulb size={25}/></span><h2>Make it work for you</h2><p>Choose any support you want. Labels are optional, and you can select more than one.</p>
      <fieldset disabled={props.busy}><legend>Tailor my tips for</legend><div className="support-needs">{SUPPORT_NEEDS.map(need => <label key={need}><input type="checkbox" checked={props.preferences.needs.includes(need)} onChange={e => props.onPreferences({ ...props.preferences, needs: e.target.checked ? [...props.preferences.needs, need] : props.preferences.needs.filter(value => value !== need) })}/><span>{need}</span></label>)}</div><small>AuDHD means autism and ADHD together.</small>
      <label className="support-field" htmlFor="reading-format">I’m reading a</label><select id="reading-format" value={props.preferences.reading} onChange={e => props.onPreferences({ ...props.preferences, reading: e.target.value as 'paper' | 'book' })}><option value="paper">Research paper</option><option value="book">Book</option></select>
      <label className="support-field" htmlFor="reading-minutes">Time I have (minutes)</label><input id="reading-minutes" type="number" min={1} max={120} step={1} value={props.preferences.minutes || ''} onChange={e => props.onPreferences({ ...props.preferences, minutes: Number(e.target.value) })}/><small>Choose 1–120 minutes. A small start counts.</small></fieldset>
      <button className="button primary" disabled={props.busy || !validTime || props.entries.length >= SUPPORT_LIMIT} onClick={() => ask('Give me a short, flexible set of focusing tips for my next reading session. Include one tiny action I can start with.')}><Sparkles size={16}/>Generate focusing tips</button>
      <p className="settings-help">No PDF needed. Uses your saved ChatGPT connection.</p><p className="settings-help">Practical reading support, not diagnosis or treatment.</p>
    </aside><section className="support-conversation" aria-label="Focusing tips conversation"><div className="support-conversation-heading"><h2><MessageSquare size={18}/>A little help getting started</h2><button className="text-button" disabled={!props.entries.length && !props.canReset} onClick={() => props.onDelete()}><Trash2 size={14}/>Clear conversation</button></div>
      <div className="support-messages" aria-live="polite" aria-relevant="additions text">{!props.entries.length && <div className="support-welcome"><span className="empty-icon"><BookOpen size={27}/></span><h2>You don’t have to force a perfect session.</h2><p>Generate a few tips, or tell ChatGPT what is getting in your way. Ask follow-ups to find something that fits.</p><div className="support-starters">{starters.map(text => <button key={text} disabled={props.busy} onClick={() => { setQuestion(text); document.getElementById('support-question')?.focus(); }}>{text}<ArrowUp size={14}/></button>)}</div></div>}
        {props.entries.map(entry => <article className="support-exchange" key={entry.id}><div className="support-question"><span>You · {entry.preferences.reading === 'paper' ? 'Paper' : 'Book'} · {entry.preferences.minutes} min{entry.preferences.needs.length ? ' · ' + entry.preferences.needs.join(', ') : ''}</span><p>{entry.question}</p><button aria-label={'Delete focusing exchange from ' + new Date(entry.createdAt).toLocaleString()} onClick={() => props.onDelete(entry.id)}><Trash2 size={14}/></button></div><div className="support-answer"><span className="answer-label"><Sparkles size={15}/>ChatGPT · {entry.model}</span>{entry.answer && <><p>{entry.answer}</p><ReadAloud id={'support-' + entry.id} text={entry.answer}/></>}{entry.status === 'pending' ? <p role="status"><LoaderCircle size={15} className="spin"/>Thinking of a manageable next step…</p> : entry.status !== 'completed' ? <p className="support-entry-status">{entry.error || (entry.status === 'cancelled' ? 'Cancelled. You can try again when you’re ready.' : 'Interrupted. Your question is saved; you can ask it again.')}<button className="text-button" disabled={props.busy} onClick={() => setQuestion(entry.question)}>Use this question</button></p> : null}</div></article>)}<div ref={answerEnd}/>
      </div><form className="support-composer" onSubmit={e => { e.preventDefault(); ask(question); }}><button type="button" className="model-choice" onClick={props.onConnection}><Sparkles size={13}/>{MODELS.find(item => item.id === props.model)?.label.split(' · ')[0] || props.model}</button><label htmlFor="support-question">Ask about focus, motivation, or your next step</label><textarea id="support-question" value={question} onChange={e => setQuestion(e.target.value)} placeholder="What makes reading hard today?" maxLength={4000} disabled={props.busy} onKeyDown={e => { if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) { e.preventDefault(); ask(question); } }}/><div className="support-send-row"><span>{props.pending ? 'Working on your reply…' : props.busy ? 'Another ChatGPT request is in progress.' : props.entries.length >= SUPPORT_LIMIT ? 'Conversation full. Clear it to start again.' : 'Follow-up questions are welcome.'}</span>{props.busy ? <button type="button" className="button" onClick={props.onCancel}>Cancel current request</button> : <button className="button primary" type="submit" disabled={!question.trim() || !validTime || props.entries.length >= SUPPORT_LIMIT}><ArrowUp size={16}/>Ask ChatGPT</button>}</div><p className="settings-help">Your chosen preferences, question, and up to 6 recent exchanges are sent to OpenAI. Normal API charges apply. This conversation is saved on this device, separately from PDF chats and exports. Clear it here at any time.</p></form>
    </section></div>
  </section>;
}
